runtime: go113

env_variables:
  INSTANCE_CONNECTION_NAME: socialmedia-287916:us-west2:socialmedia-project
  DB_USER: root
  DB_PASS: 1234
  DB_NAME: socialmedia
  GOOGLE_APPLICATION_CREDENTIALS: "./massive-team-279205-069c46519860.json"